### ISSUE TITLE
[question] Running on headless servers?

### ISSUE THREAD

**Issue by johnheroy** [kayahr/jest-electron-runner#16]
Thanks for making this project. I am looking to use it to run tests on CI servers but have an issue with headless machines (GitHub's `ubuntu-latest` runner). I have tried to use `xvfb` to stub the window server piece but get this error:

```
[1964:0315/172300.476076:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[1964:0315/172300.476237:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
```

I've set DISPLAY in my environment to the port xvfb is running on - is there some other way to pass it in as an env variable?

A snippet from my action yaml:

```
env:
  DISPLAY: :99.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install in-memory window server (for electron tests)
        run: sudo apt-get install -y xvfb
      - name: Start xvfb
        run: xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - run: echo $DISPLAY # this works
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
```

**Comment by johnheroy** [comment]
I'm also not beholden to `xvfb` in any way but it seemed like a common solution for electron or browser-based tests for CI pipelines. Thank you!

**Comment by johnheroy** [comment]
I've "fixed" this with using `xvfb-run ... { test command }` but get a new error:

```
[2309:0315/181315.952636:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2309:0315/181315.952683:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
```

**Comment by lancedikson** [comment]
Hi @johnheroy! I've just encountered the same issue — electron-runner doesn't seem to work on Linux build for some reason. Did you happen to resolve the issue in the end? Could you maybe share the solution you used? 🙏

**Comment by johnheroy** [comment]
Hey @lancedikson I ended up just using `xvfb-run` fine but ignoring these errors - the jest-electron-runner still seems to work as intended 🤷

**Comment by lancedikson** [comment]
Alright, thanks for the quick answer! Great that it still works fine! Thank you for sharing your solution as well!

**Comment by decanTyme** [comment]
Thought I'd share how I solved this in my CI workflow (also GH Actions):

```yaml
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: "lts/*"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # https://github.com/marketplace/actions/setup-xvfb
      - uses: coactions/setup-xvfb@v1
        with:
          run: yarn test
```

Likewise ignored the new errors as it also seemed to work regardless.
